### ISSUE TITLE
App crashes on adding new show because of punt page

### ISSUE THREAD

**Issue by heyjaywilson** [maeganjwilson/iHog#56]
Need to look into a bit more as to why

**Comment by appsbymw** [comment]
This no longer occurs, but is not "closed" due to it just happens. Not locked by purchase.

**Comment by heyjaywilson** [comment]
Closing since it does what it is supposed to do.

**Comment by heyjaywilson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [App crashes on adding new show because of punt page](https://trello.com/c/phqB3HR9/15-app-crashes-on-adding-new-show-because-of-punt-page)
